apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: db:5432
    database: app
    user: postgres
    secureJsonData:
      password: 'changethis'
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
    editable: true