"""Update gas and oil prices tables schema

Revision ID: 02d7d7be9161
Revises: 707b42975f12
Create Date: 2026-03-09 07:36:02.704499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '02d7d7be9161'
down_revision: Union[str, Sequence[str], None] = '707b42975f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gas_prices', sa.Column('cena_pln', sa.Float(), nullable=True))
    op.add_column('gas_prices', sa.Column('cena_eur', sa.Float(), nullable=True))
    op.add_column('gas_prices', sa.Column('volume', sa.Float(), nullable=True))
    op.add_column('gas_prices', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint(op.f('uq_gas_prices_data'), 'gas_prices', type_='unique')
    op.create_unique_constraint('uq_gas_prices_data_source', 'gas_prices', ['data', 'source'])
    op.drop_column('gas_prices', 'cena_pln_mwh')
    op.drop_column('gas_prices', 'cena_eur_mwh')
    op.add_column('oil_prices', sa.Column('cena_usd', sa.Float(), nullable=True))
    op.add_column('oil_prices', sa.Column('cena_pln', sa.Float(), nullable=True))
    op.add_column('oil_prices', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint(op.f('uq_oil_prices_data'), 'oil_prices', type_='unique')
    op.create_unique_constraint('uq_oil_prices_data_source', 'oil_prices', ['data', 'source'])
    op.drop_column('oil_prices', 'cena_usd_baryłka')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oil_prices', sa.Column('cena_usd_baryłka', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint('uq_oil_prices_data_source', 'oil_prices', type_='unique')
    op.create_unique_constraint(op.f('uq_oil_prices_data'), 'oil_prices', ['data'], postgresql_nulls_not_distinct=False)
    op.drop_column('oil_prices', 'source')
    op.drop_column('oil_prices', 'cena_pln')
    op.drop_column('oil_prices', 'cena_usd')
    op.add_column('gas_prices', sa.Column('cena_eur_mwh', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('gas_prices', sa.Column('cena_pln_mwh', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint('uq_gas_prices_data_source', 'gas_prices', type_='unique')
    op.create_unique_constraint(op.f('uq_gas_prices_data'), 'gas_prices', ['data'], postgresql_nulls_not_distinct=False)
    op.drop_column('gas_prices', 'source')
    op.drop_column('gas_prices', 'volume')
    op.drop_column('gas_prices', 'cena_eur')
    op.drop_column('gas_prices', 'cena_pln')
    # ### end Alembic commands ###
