"""Full Setup3

Revision ID: 0571d7bde939
Revises: ec741e9f1a4f
Create Date: 2025-12-05 21:49:24.416561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0571d7bde939'
down_revision: Union[str, Sequence[str], None] = 'ec741e9f1a4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_crb_doba_udtczas'), 'crb_rozliczenia', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_crb_doba_udtczas'), 'crb_rozliczenia', ['doba', 'udtczas'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
