"""add_ml_feature_store

Revision ID: 55d5a145e349
Revises: b3e7f9a2c1d8
Create Date: 2026-03-16 07:36:58.178447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '55d5a145e349'
down_revision: Union[str, Sequence[str], None] = 'b3e7f9a2c1d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('business_date', sa.DateTime(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.Column('is_peak_hour', sa.Boolean(), nullable=False),
    sa.Column('demand_mw', sa.Float(), nullable=True),
    sa.Column('rce_pln', sa.Float(), nullable=True),
    sa.Column('gen_wind_mw', sa.Float(), nullable=True),
    sa.Column('gen_solar_mw', sa.Float(), nullable=True),
    sa.Column('gen_coal_mw', sa.Float(), nullable=True),
    sa.Column('gen_renewables_mw', sa.Float(), nullable=True),
    sa.Column('gen_total_mw', sa.Float(), nullable=True),
    sa.Column('renewable_share', sa.Float(), nullable=True),
    sa.Column('flow_pl_de', sa.Float(), nullable=True),
    sa.Column('flow_pl_cz', sa.Float(), nullable=True),
    sa.Column('flow_pl_sk', sa.Float(), nullable=True),
    sa.Column('flow_pl_se', sa.Float(), nullable=True),
    sa.Column('flow_pl_lt', sa.Float(), nullable=True),
    sa.Column('flow_net', sa.Float(), nullable=True),
    sa.Column('market_position_sk', sa.Float(), nullable=True),
    sa.Column('sdac_pln', sa.Float(), nullable=True),
    sa.Column('intraday_rbn_vol', sa.Float(), nullable=True),
    sa.Column('intraday_rbb_vol', sa.Float(), nullable=True),
    sa.Column('crb_cen_cost', sa.Float(), nullable=True),
    sa.Column('crb_ckoeb_cost', sa.Float(), nullable=True),
    sa.Column('co2_pln', sa.Float(), nullable=True),
    sa.Column('oil_usd', sa.Float(), nullable=True),
    sa.Column('temp_forecast', sa.Float(), nullable=True),
    sa.Column('wind_speed_forecast', sa.Float(), nullable=True),
    sa.Column('humidity_forecast', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts', name='uq_ml_features_ts')
    )
    op.create_index('idx_ml_features_business_date', 'ml_features', ['business_date'], unique=False)
    op.create_index('idx_ml_features_ts', 'ml_features', ['ts'], unique=False)
    op.create_index(op.f('ix_ml_features_ts'), 'ml_features', ['ts'], unique=False)
    op.create_table('model_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('parameters', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('training_data_from', sa.Date(), nullable=True),
    sa.Column('training_data_to', sa.Date(), nullable=True),
    sa.Column('feature_importance', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('validation_score', sa.Float(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('r2_score', sa.Float(), nullable=True),
    sa.Column('model_file_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_metadata_model_name'), 'model_metadata', ['model_name'], unique=False)
    op.create_index(op.f('ix_model_metadata_version'), 'model_metadata', ['version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_metadata_version'), table_name='model_metadata')
    op.drop_index(op.f('ix_model_metadata_model_name'), table_name='model_metadata')
    op.drop_table('model_metadata')
    op.drop_index(op.f('ix_ml_features_ts'), table_name='ml_features')
    op.drop_index('idx_ml_features_ts', table_name='ml_features')
    op.drop_index('idx_ml_features_business_date', table_name='ml_features')
    op.drop_table('ml_features')
    # ### end Alembic commands ###
