"""Full Setup7

Revision ID: 6d501e402cd3
Revises: f3b56275a051
Create Date: 2025-12-05 22:01:26.953965

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d501e402cd3'
down_revision: Union[str, Sequence[str], None] = 'f3b56275a051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_crb_doba_udtczas'), 'crb_rozliczenia', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_crb_doba_udtczas'), 'crb_rozliczenia', ['doba', 'udtczas_oreb'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
