"""Add gas and oil prices tables

Revision ID: 707b42975f12
Revises: b3adc48319e8
Create Date: 2026-03-09 06:09:06.330096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '707b42975f12'
down_revision: Union[str, Sequence[str], None] = 'b3adc48319e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gas_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('cena_pln_mwh', sa.Float(), nullable=False),
    sa.Column('cena_eur_mwh', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data', name='uq_gas_prices_data')
    )
    op.create_index('idx_gas_prices_data', 'gas_prices', ['data'], unique=False)
    op.create_index(op.f('ix_gas_prices_data'), 'gas_prices', ['data'], unique=False)
    op.create_table('oil_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('cena_usd_baryłka', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data', name='uq_oil_prices_data')
    )
    op.create_index('idx_oil_prices_data', 'oil_prices', ['data'], unique=False)
    op.create_index(op.f('ix_oil_prices_data'), 'oil_prices', ['data'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oil_prices_data'), table_name='oil_prices')
    op.drop_index('idx_oil_prices_data', table_name='oil_prices')
    op.drop_table('oil_prices')
    op.drop_index(op.f('ix_gas_prices_data'), table_name='gas_prices')
    op.drop_index('idx_gas_prices_data', table_name='gas_prices')
    op.drop_table('gas_prices')
    # ### end Alembic commands ###
