"""empty message

Revision ID: 75d679ac2464
Revises: 20260318_add_gas
Create Date: 2026-03-19 12:02:41.304435

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '75d679ac2464'
down_revision: Union[str, Sequence[str], None] = '20260318_add_gas'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_forecast', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('weather_forecast', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('weather_forecast', sa.Column('forecast_datetime', sa.DateTime(), nullable=True))
    op.add_column('weather_forecast', sa.Column('temperature_2m', sa.Float(), nullable=True))
    op.add_column('weather_forecast', sa.Column('rain', sa.Float(), nullable=True))
    op.add_column('weather_forecast', sa.Column('relative_humidity_2m', sa.Float(), nullable=True))
    op.add_column('weather_forecast', sa.Column('precipitation', sa.Float(), nullable=True))
    op.add_column('weather_forecast', sa.Column('wind_speed_10m', sa.Float(), nullable=True))
    op.add_column('weather_forecast', sa.Column('wind_direction_10m', sa.Float(), nullable=True))
    op.add_column('weather_forecast', sa.Column('ghi', sa.Float(), nullable=True))
    op.add_column('weather_forecast', sa.Column('dni', sa.Float(), nullable=True))
    op.add_column('weather_forecast', sa.Column('dri', sa.Float(), nullable=True))
    op.add_column('weather_forecast', sa.Column('gti', sa.Float(), nullable=True))
    op.add_column('weather_forecast', sa.Column('terrestrial_radiation', sa.Float(), nullable=True))
    op.add_column('weather_forecast', sa.Column('datasource', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE weather_forecast SET datasource = 'openmeteo'")
    op.alter_column('weather_forecast', 'datasource', nullable=False)
    op.drop_index(op.f('idx_pogoda_prog_data_pobrania'), table_name='weather_forecast')
    op.drop_index(op.f('idx_pogoda_prog_stacja_dzien'), table_name='weather_forecast')
    op.drop_constraint(op.f('uq_weather_forecast_stacja_czas'), 'weather_forecast', type_='unique')
    op.create_index('idx_weather_forecast_coords', 'weather_forecast', ['latitude', 'longitude'], unique=False)
    op.create_index('idx_weather_forecast_datetime', 'weather_forecast', ['forecast_datetime'], unique=False)
    op.create_unique_constraint('uq_weather_forecast_coords_time', 'weather_forecast', ['latitude', 'longitude', 'forecast_datetime'])
    op.drop_column('weather_forecast', 'temperatura_prognoza')
    op.drop_column('weather_forecast', 'data_pobrania_prognozy')
    op.drop_column('weather_forecast', 'dzien_prognozy')
    op.drop_column('weather_forecast', 'zachmurzenie_prognoza')
    op.drop_column('weather_forecast', 'czas_prognozy')
    op.drop_column('weather_forecast', 'szansa_opadu')
    op.drop_column('weather_forecast', 'stacja_nazwa')
    op.drop_column('weather_forecast', 'wilgotnosc_prognoza')
    op.drop_column('weather_forecast', 'predkosc_wiatru_prognoza')
    op.drop_column('weather_forecast', 'kierunek_wiatru_prognoza')
    op.drop_column('weather_forecast', 'wielkosc_opadu_prognoza')
    op.drop_column('weather_forecast', 'zrodlo_prognozy')
    op.drop_column('weather_forecast', 'cisnienie_prognoza')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_forecast', sa.Column('cisnienie_prognoza', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('weather_forecast', sa.Column('zrodlo_prognozy', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('weather_forecast', sa.Column('wielkosc_opadu_prognoza', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('weather_forecast', sa.Column('kierunek_wiatru_prognoza', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('weather_forecast', sa.Column('predkosc_wiatru_prognoza', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('weather_forecast', sa.Column('wilgotnosc_prognoza', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('weather_forecast', sa.Column('stacja_nazwa', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('weather_forecast', sa.Column('szansa_opadu', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('weather_forecast', sa.Column('czas_prognozy', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('weather_forecast', sa.Column('zachmurzenie_prognoza', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('weather_forecast', sa.Column('dzien_prognozy', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('weather_forecast', sa.Column('data_pobrania_prognozy', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('weather_forecast', sa.Column('temperatura_prognoza', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint('uq_weather_forecast_coords_time', 'weather_forecast', type_='unique')
    op.drop_index('idx_weather_forecast_datetime', table_name='weather_forecast')
    op.drop_index('idx_weather_forecast_coords', table_name='weather_forecast')
    op.create_unique_constraint(op.f('uq_weather_forecast_stacja_czas'), 'weather_forecast', ['stacja_nazwa', 'czas_prognozy'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_pogoda_prog_stacja_dzien'), 'weather_forecast', ['stacja_nazwa', 'dzien_prognozy'], unique=False)
    op.create_index(op.f('idx_pogoda_prog_data_pobrania'), 'weather_forecast', ['data_pobrania_prognozy'], unique=False)
    op.drop_column('weather_forecast', 'datasource')
    op.drop_column('weather_forecast', 'terrestrial_radiation')
    op.drop_column('weather_forecast', 'gti')
    op.drop_column('weather_forecast', 'dri')
    op.drop_column('weather_forecast', 'dni')
    op.drop_column('weather_forecast', 'ghi')
    op.drop_column('weather_forecast', 'wind_direction_10m')
    op.drop_column('weather_forecast', 'wind_speed_10m')
    op.drop_column('weather_forecast', 'precipitation')
    op.drop_column('weather_forecast', 'relative_humidity_2m')
    op.drop_column('weather_forecast', 'rain')
    op.drop_column('weather_forecast', 'temperature_2m')
    op.drop_column('weather_forecast', 'forecast_datetime')
    op.drop_column('weather_forecast', 'longitude')
    op.drop_column('weather_forecast', 'latitude')
    # ### end Alembic commands ###
