"""Add unique constraint to co2_prices business_date

Revision ID: 7f3f802d357f
Revises: a8ca99934306
Create Date: 2026-03-09 11:27:30.515561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f3f802d357f'
down_revision: Union[str, Sequence[str], None] = 'a8ca99934306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_co2_prices_business_date', 'co2_prices', ['business_date'], unique=False)
    op.create_unique_constraint('uq_co2_prices_business_date', 'co2_prices', ['business_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_co2_prices_business_date', 'co2_prices', type_='unique')
    op.drop_index('idx_co2_prices_business_date', table_name='co2_prices')
    # ### end Alembic commands ###
