"""Update unique constraint for power flows to include business_date

Revision ID: a8ca99934306
Revises: 47168fd002dd
Create Date: 2026-03-09 11:21:52.709338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8ca99934306'
down_revision: Union[str, Sequence[str], None] = '47168fd002dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_power_flows_section_dtime'), 'unit_power_flows', type_='unique')
    op.create_unique_constraint('uq_power_flows_section_dtime_biz', 'unit_power_flows', ['section_code', 'dtime', 'business_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_power_flows_section_dtime_biz', 'unit_power_flows', type_='unique')
    op.create_unique_constraint(op.f('uq_power_flows_section_dtime'), 'unit_power_flows', ['section_code', 'dtime'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
