"""Fix unit_power_flows table schema

Revision ID: a94df5087204
Revises: prediction_system_v1
Create Date: 2026-03-09 11:17:21.795220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a94df5087204'
down_revision: Union[str, Sequence[str], None] = 'prediction_system_v1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('co2_prices_doba_key'), 'co2_prices', type_='unique')
    op.drop_column('co2_prices', 'doba')
    op.add_column('crb_rozliczenia', sa.Column('dtime', sa.DateTime(), nullable=False))
    op.add_column('crb_rozliczenia', sa.Column('dtime_utc', sa.DateTime(), nullable=False))
    op.add_column('crb_rozliczenia', sa.Column('period', sa.String(), nullable=False))
    op.add_column('crb_rozliczenia', sa.Column('period_utc', sa.String(), nullable=False))
    op.add_column('crb_rozliczenia', sa.Column('cen_cost', sa.Float(), nullable=False))
    op.add_column('crb_rozliczenia', sa.Column('ckoeb_cost', sa.Float(), nullable=False))
    op.add_column('crb_rozliczenia', sa.Column('ceb_pp_cost', sa.Float(), nullable=False))
    op.add_column('crb_rozliczenia', sa.Column('ceb_sr_cost', sa.Float(), nullable=False))
    op.add_column('crb_rozliczenia', sa.Column('ceb_sr_afrrd_cost', sa.Float(), nullable=True))
    op.add_column('crb_rozliczenia', sa.Column('ceb_sr_afrrg_cost', sa.Float(), nullable=True))
    op.add_column('crb_rozliczenia', sa.Column('publication_ts', sa.DateTime(), nullable=False))
    op.add_column('crb_rozliczenia', sa.Column('publication_ts_utc', sa.DateTime(), nullable=False))
    op.drop_index(op.f('idx_crb_doba_biz'), table_name='crb_rozliczenia')
    op.drop_index(op.f('ix_crb_rozliczenia_doba'), table_name='crb_rozliczenia')
    op.create_index('idx_crb_dtime_biz', 'crb_rozliczenia', ['dtime', 'business_date'], unique=False)
    op.create_index(op.f('ix_crb_rozliczenia_dtime'), 'crb_rozliczenia', ['dtime'], unique=False)
    op.create_unique_constraint('uq_crb_dtime_period', 'crb_rozliczenia', ['dtime', 'period'])
    op.drop_column('crb_rozliczenia', 'cen_rozl')
    op.drop_column('crb_rozliczenia', 'doba')
    op.drop_column('crb_rozliczenia', 'ceb_sr_rozl')
    op.drop_column('crb_rozliczenia', 'ceb_pp_rozl')
    op.drop_column('crb_rozliczenia', 'ckoeb_rozl')
    op.drop_column('crb_rozliczenia', 'created_at')
    op.drop_column('crb_rozliczenia', 'source_datetime')
    op.drop_column('crb_rozliczenia', 'updated_at')
    op.drop_column('crb_rozliczenia', 'udtczas_oreb')
    op.add_column('energy_price_predictions', sa.Column('target_date', sa.DateTime(), nullable=False))
    op.add_column('energy_price_predictions', sa.Column('model_accuracy', sa.Float(), nullable=True))
    op.alter_column('energy_price_predictions', 'prediction_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='Data dla której jest predykcja',
               existing_nullable=False)
    op.alter_column('energy_price_predictions', 'predicted_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               comment=None,
               existing_comment='Przewidywana cena',
               existing_nullable=False)
    op.alter_column('energy_price_predictions', 'confidence_lower',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               comment=None,
               existing_comment='Dolna granica confidence interval',
               existing_nullable=True)
    op.alter_column('energy_price_predictions', 'confidence_upper',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               comment=None,
               existing_comment='Górna granica confidence interval',
               existing_nullable=True)
    op.alter_column('energy_price_predictions', 'model_version',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Wersja modelu użytego do predykcji',
               existing_nullable=False)
    op.drop_index(op.f('ix_energy_price_predictions_created_at'), table_name='energy_price_predictions')
    op.drop_index(op.f('ix_energy_price_predictions_model_version'), table_name='energy_price_predictions')
    op.drop_constraint(op.f('uq_prediction_date_model'), 'energy_price_predictions', type_='unique')
    op.create_index('idx_predictions_created', 'energy_price_predictions', ['prediction_date'], unique=False)
    op.create_index('idx_predictions_target_date', 'energy_price_predictions', ['target_date'], unique=False)
    op.create_index(op.f('ix_energy_price_predictions_target_date'), 'energy_price_predictions', ['target_date'], unique=False)
    op.create_unique_constraint('uq_predictions_dates', 'energy_price_predictions', ['prediction_date', 'target_date'])
    op.drop_table_comment(
        'energy_price_predictions',
        existing_comment='Tabela z predykcjami cen energii wygenerowanymi przez modele ML',
        schema=None
    )
    op.drop_column('energy_price_predictions', 'features_used')
    op.add_column('model_metadata', sa.Column('model_type', sa.String(), nullable=False))
    op.add_column('model_metadata', sa.Column('training_data_size', sa.Integer(), nullable=False))
    op.add_column('model_metadata', sa.Column('feature_count', sa.Integer(), nullable=False))
    op.add_column('model_metadata', sa.Column('training_duration_seconds', sa.Float(), nullable=False))
    op.add_column('model_metadata', sa.Column('trained_at', sa.DateTime(), nullable=False))
    op.alter_column('model_metadata', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Nazwa modelu (np. RandomForest, GradientBoosting)',
               existing_nullable=False)
    op.alter_column('model_metadata', 'version',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Wersja modelu',
               existing_nullable=False)
    op.alter_column('model_metadata', 'r2_score',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Float(),
               nullable=False,
               comment=None,
               existing_comment='R² Score')
    op.alter_column('model_metadata', 'mae',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False,
               comment=None,
               existing_comment='Mean Absolute Error')
    op.alter_column('model_metadata', 'rmse',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False,
               comment=None,
               existing_comment='Root Mean Square Error')
    op.alter_column('model_metadata', 'model_file_path',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Ścieżka do zapisanego modelu',
               existing_nullable=True)
    op.alter_column('model_metadata', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Czy model jest aktywny',
               existing_nullable=False)
    op.drop_index(op.f('ix_model_metadata_created_at'), table_name='model_metadata')
    op.drop_index(op.f('ix_model_metadata_is_active'), table_name='model_metadata')
    op.drop_index(op.f('ix_model_metadata_version'), table_name='model_metadata')
    op.create_index('idx_model_trained_at', 'model_metadata', ['trained_at'], unique=False)
    op.create_index(op.f('ix_model_metadata_trained_at'), 'model_metadata', ['trained_at'], unique=False)
    op.drop_table_comment(
        'model_metadata',
        existing_comment='Metadane modeli ML używanych do predykcji cen energii',
        schema=None
    )
    op.drop_column('model_metadata', 'training_data_to')
    op.drop_column('model_metadata', 'parameters')
    op.drop_column('model_metadata', 'validation_score')
    op.drop_column('model_metadata', 'training_data_from')
    op.drop_column('model_metadata', 'feature_importance')
    op.add_column('unit_power_flows', sa.Column('section_code', sa.String(), nullable=False))
    op.add_column('unit_power_flows', sa.Column('dtime', sa.DateTime(), nullable=False))
    op.add_column('unit_power_flows', sa.Column('dtime_utc', sa.DateTime(), nullable=False))
    op.add_column('unit_power_flows', sa.Column('period', sa.String(), nullable=False))
    op.add_column('unit_power_flows', sa.Column('period_utc', sa.String(), nullable=False))
    op.add_column('unit_power_flows', sa.Column('value', sa.Float(), nullable=False))
    op.add_column('unit_power_flows', sa.Column('publication_ts', sa.DateTime(), nullable=False))
    op.add_column('unit_power_flows', sa.Column('publication_ts_utc', sa.DateTime(), nullable=False))
    op.create_index('idx_power_flows_business_date', 'unit_power_flows', ['business_date'], unique=False)
    op.create_index('idx_power_flows_section', 'unit_power_flows', ['section_code'], unique=False)
    op.create_index(op.f('ix_unit_power_flows_business_date'), 'unit_power_flows', ['business_date'], unique=False)
    op.create_index(op.f('ix_unit_power_flows_section_code'), 'unit_power_flows', ['section_code'], unique=False)
    op.create_unique_constraint('uq_power_flows_section_dtime', 'unit_power_flows', ['section_code', 'dtime'])
    op.drop_column('unit_power_flows', 'doba')
    op.drop_column('unit_power_flows', 'wartosc')
    op.drop_column('unit_power_flows', 'udtczas')
    op.drop_column('unit_power_flows', 'source_datetime')
    op.drop_column('unit_power_flows', 'kod_przekroju')
    op.drop_column('unit_power_flows', 'udtczas_oreb')
    op.add_column('unit_power_losses', sa.Column('resource_code', sa.String(), nullable=False))
    op.add_column('unit_power_losses', sa.Column('power_plant', sa.String(), nullable=False))
    op.add_column('unit_power_losses', sa.Column('dtime', sa.DateTime(), nullable=False))
    op.add_column('unit_power_losses', sa.Column('dtime_utc', sa.DateTime(), nullable=False))
    op.add_column('unit_power_losses', sa.Column('period', sa.String(), nullable=False))
    op.add_column('unit_power_losses', sa.Column('period_utc', sa.String(), nullable=False))
    op.add_column('unit_power_losses', sa.Column('grid_lim', sa.Float(), nullable=False))
    op.add_column('unit_power_losses', sa.Column('non_us_cap', sa.Float(), nullable=False))
    op.add_column('unit_power_losses', sa.Column('available_capacity', sa.Float(), nullable=False))
    op.add_column('unit_power_losses', sa.Column('publication_ts', sa.DateTime(), nullable=False))
    op.add_column('unit_power_losses', sa.Column('publication_ts_utc', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_unit_power_losses_resource_code'), 'unit_power_losses', ['resource_code'], unique=False)
    op.drop_column('unit_power_losses', 'odtczas')
    op.drop_column('unit_power_losses', 'dost_zdool')
    op.drop_column('unit_power_losses', 'ub_siec')
    op.drop_column('unit_power_losses', 'source_datetime')
    op.drop_column('unit_power_losses', 'kod_jg')
    op.drop_column('unit_power_losses', 'ub_elek')
    op.drop_column('unit_power_losses', 'elektrownia')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit_power_losses', sa.Column('elektrownia', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('unit_power_losses', sa.Column('ub_elek', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('unit_power_losses', sa.Column('kod_jg', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('unit_power_losses', sa.Column('source_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('unit_power_losses', sa.Column('ub_siec', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('unit_power_losses', sa.Column('dost_zdool', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('unit_power_losses', sa.Column('odtczas', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_unit_power_losses_resource_code'), table_name='unit_power_losses')
    op.drop_column('unit_power_losses', 'publication_ts_utc')
    op.drop_column('unit_power_losses', 'publication_ts')
    op.drop_column('unit_power_losses', 'available_capacity')
    op.drop_column('unit_power_losses', 'non_us_cap')
    op.drop_column('unit_power_losses', 'grid_lim')
    op.drop_column('unit_power_losses', 'period_utc')
    op.drop_column('unit_power_losses', 'period')
    op.drop_column('unit_power_losses', 'dtime_utc')
    op.drop_column('unit_power_losses', 'dtime')
    op.drop_column('unit_power_losses', 'power_plant')
    op.drop_column('unit_power_losses', 'resource_code')
    op.add_column('unit_power_flows', sa.Column('udtczas_oreb', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('unit_power_flows', sa.Column('kod_przekroju', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('unit_power_flows', sa.Column('source_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('unit_power_flows', sa.Column('udtczas', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('unit_power_flows', sa.Column('wartosc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('unit_power_flows', sa.Column('doba', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_power_flows_section_dtime', 'unit_power_flows', type_='unique')
    op.drop_index(op.f('ix_unit_power_flows_section_code'), table_name='unit_power_flows')
    op.drop_index(op.f('ix_unit_power_flows_business_date'), table_name='unit_power_flows')
    op.drop_index('idx_power_flows_section', table_name='unit_power_flows')
    op.drop_index('idx_power_flows_business_date', table_name='unit_power_flows')
    op.drop_column('unit_power_flows', 'publication_ts_utc')
    op.drop_column('unit_power_flows', 'publication_ts')
    op.drop_column('unit_power_flows', 'value')
    op.drop_column('unit_power_flows', 'period_utc')
    op.drop_column('unit_power_flows', 'period')
    op.drop_column('unit_power_flows', 'dtime_utc')
    op.drop_column('unit_power_flows', 'dtime')
    op.drop_column('unit_power_flows', 'section_code')
    op.add_column('model_metadata', sa.Column('feature_importance', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Ważność features jako JSON'))
    op.add_column('model_metadata', sa.Column('training_data_from', sa.DATE(), autoincrement=False, nullable=True, comment='Początek okresu danych treningowych'))
    op.add_column('model_metadata', sa.Column('validation_score', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True, comment='Wynik walidacji modelu'))
    op.add_column('model_metadata', sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Parametry modelu jako JSON'))
    op.add_column('model_metadata', sa.Column('training_data_to', sa.DATE(), autoincrement=False, nullable=True, comment='Koniec okresu danych treningowych'))
    op.create_table_comment(
        'model_metadata',
        'Metadane modeli ML używanych do predykcji cen energii',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_model_metadata_trained_at'), table_name='model_metadata')
    op.drop_index('idx_model_trained_at', table_name='model_metadata')
    op.create_index(op.f('ix_model_metadata_version'), 'model_metadata', ['version'], unique=False)
    op.create_index(op.f('ix_model_metadata_is_active'), 'model_metadata', ['is_active'], unique=False)
    op.create_index(op.f('ix_model_metadata_created_at'), 'model_metadata', ['created_at'], unique=False)
    op.alter_column('model_metadata', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Czy model jest aktywny',
               existing_nullable=False)
    op.alter_column('model_metadata', 'model_file_path',
               existing_type=sa.VARCHAR(length=500),
               comment='Ścieżka do zapisanego modelu',
               existing_nullable=True)
    op.alter_column('model_metadata', 'rmse',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               comment='Root Mean Square Error')
    op.alter_column('model_metadata', 'mae',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               comment='Mean Absolute Error')
    op.alter_column('model_metadata', 'r2_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=6),
               nullable=True,
               comment='R² Score')
    op.alter_column('model_metadata', 'version',
               existing_type=sa.VARCHAR(length=50),
               comment='Wersja modelu',
               existing_nullable=False)
    op.alter_column('model_metadata', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Nazwa modelu (np. RandomForest, GradientBoosting)',
               existing_nullable=False)
    op.drop_column('model_metadata', 'trained_at')
    op.drop_column('model_metadata', 'training_duration_seconds')
    op.drop_column('model_metadata', 'feature_count')
    op.drop_column('model_metadata', 'training_data_size')
    op.drop_column('model_metadata', 'model_type')
    op.add_column('energy_price_predictions', sa.Column('features_used', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='JSON z listą features użytych w modelu'))
    op.create_table_comment(
        'energy_price_predictions',
        'Tabela z predykcjami cen energii wygenerowanymi przez modele ML',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint('uq_predictions_dates', 'energy_price_predictions', type_='unique')
    op.drop_index(op.f('ix_energy_price_predictions_target_date'), table_name='energy_price_predictions')
    op.drop_index('idx_predictions_target_date', table_name='energy_price_predictions')
    op.drop_index('idx_predictions_created', table_name='energy_price_predictions')
    op.create_unique_constraint(op.f('uq_prediction_date_model'), 'energy_price_predictions', ['prediction_date', 'model_version'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_energy_price_predictions_model_version'), 'energy_price_predictions', ['model_version'], unique=False)
    op.create_index(op.f('ix_energy_price_predictions_created_at'), 'energy_price_predictions', ['created_at'], unique=False)
    op.alter_column('energy_price_predictions', 'model_version',
               existing_type=sa.VARCHAR(length=50),
               comment='Wersja modelu użytego do predykcji',
               existing_nullable=False)
    op.alter_column('energy_price_predictions', 'confidence_upper',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               comment='Górna granica confidence interval',
               existing_nullable=True)
    op.alter_column('energy_price_predictions', 'confidence_lower',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               comment='Dolna granica confidence interval',
               existing_nullable=True)
    op.alter_column('energy_price_predictions', 'predicted_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               comment='Przewidywana cena',
               existing_nullable=False)
    op.alter_column('energy_price_predictions', 'prediction_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               comment='Data dla której jest predykcja',
               existing_nullable=False)
    op.drop_column('energy_price_predictions', 'model_accuracy')
    op.drop_column('energy_price_predictions', 'target_date')
    op.add_column('crb_rozliczenia', sa.Column('udtczas_oreb', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('crb_rozliczenia', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('crb_rozliczenia', sa.Column('source_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('crb_rozliczenia', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('crb_rozliczenia', sa.Column('ckoeb_rozl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('crb_rozliczenia', sa.Column('ceb_pp_rozl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('crb_rozliczenia', sa.Column('ceb_sr_rozl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('crb_rozliczenia', sa.Column('doba', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('crb_rozliczenia', sa.Column('cen_rozl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint('uq_crb_dtime_period', 'crb_rozliczenia', type_='unique')
    op.drop_index(op.f('ix_crb_rozliczenia_dtime'), table_name='crb_rozliczenia')
    op.drop_index('idx_crb_dtime_biz', table_name='crb_rozliczenia')
    op.create_index(op.f('ix_crb_rozliczenia_doba'), 'crb_rozliczenia', ['doba'], unique=False)
    op.create_index(op.f('idx_crb_doba_biz'), 'crb_rozliczenia', ['doba', 'business_date'], unique=False)
    op.drop_column('crb_rozliczenia', 'publication_ts_utc')
    op.drop_column('crb_rozliczenia', 'publication_ts')
    op.drop_column('crb_rozliczenia', 'ceb_sr_afrrg_cost')
    op.drop_column('crb_rozliczenia', 'ceb_sr_afrrd_cost')
    op.drop_column('crb_rozliczenia', 'ceb_sr_cost')
    op.drop_column('crb_rozliczenia', 'ceb_pp_cost')
    op.drop_column('crb_rozliczenia', 'ckoeb_cost')
    op.drop_column('crb_rozliczenia', 'cen_cost')
    op.drop_column('crb_rozliczenia', 'period_utc')
    op.drop_column('crb_rozliczenia', 'period')
    op.drop_column('crb_rozliczenia', 'dtime_utc')
    op.drop_column('crb_rozliczenia', 'dtime')
    op.add_column('co2_prices', sa.Column('doba', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('co2_prices_doba_key'), 'co2_prices', ['doba'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
