"""Full Setup

Revision ID: b9e8426fe4be
Revises: 
Create Date: 2025-12-05 19:08:40.043083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b9e8426fe4be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('co2_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doba', sa.DateTime(), nullable=False),
    sa.Column('rcco2_eur', sa.Float(), nullable=False),
    sa.Column('rcco2_pln', sa.Float(), nullable=False),
    sa.Column('business_date', sa.DateTime(), nullable=False),
    sa.Column('source_datetime', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doba')
    )
    op.create_table('energy_price_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_date', sa.DateTime(), nullable=False),
    sa.Column('prognoza_cena_mwh', sa.Float(), nullable=False),
    sa.Column('godzina', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('publication_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_price_forecasts_forecast_date'), 'energy_price_forecasts', ['forecast_date'], unique=False)
    op.create_table('energy_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doba', sa.DateTime(), nullable=False),
    sa.Column('cena_mwh', sa.Float(), nullable=False),
    sa.Column('godzina', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('business_date', sa.DateTime(), nullable=False),
    sa.Column('source_datetime', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doba', 'godzina', name='uq_energy_price_doba_godzina')
    )
    op.create_index('idx_energy_price_doba_biz', 'energy_prices', ['doba', 'business_date'], unique=False)
    op.create_table('error_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stacja_nazwa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('dni_wyprzedzenia', sa.Integer(), nullable=False),
    sa.Column('blad_temperatury', sa.Float(), nullable=False),
    sa.Column('blad_wiatru', sa.Float(), nullable=False),
    sa.Column('blad_opadow', sa.Float(), nullable=False),
    sa.Column('blad_zachmurzenia', sa.Float(), nullable=False),
    sa.Column('czy_prognoza_byla_dokladna', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analyza_bledow_stacja_dni', 'error_analysis', ['stacja_nazwa', 'dni_wyprzedzenia'], unique=False)
    op.create_table('system_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doba', sa.DateTime(), nullable=False),
    sa.Column('temperatura', sa.Float(), nullable=True),
    sa.Column('predkosc_wiatru', sa.Float(), nullable=True),
    sa.Column('zamoralowienie', sa.Float(), nullable=True),
    sa.Column('prognoza_popytu', sa.Float(), nullable=True),
    sa.Column('produkcja_oze', sa.Float(), nullable=True),
    sa.Column('godzina', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_data_doba'), 'system_data', ['doba'], unique=False)
    op.create_table('unit_power_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doba', sa.DateTime(), nullable=False),
    sa.Column('udtczas', sa.DateTime(), nullable=False),
    sa.Column('wartosc', sa.Float(), nullable=False),
    sa.Column('udtczas_oreb', sa.DateTime(), nullable=False),
    sa.Column('business_date', sa.DateTime(), nullable=False),
    sa.Column('kod_przekroju', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_power_losses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kod_jg', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ub_elek', sa.Float(), nullable=False),
    sa.Column('ub_siec', sa.Float(), nullable=False),
    sa.Column('odtczas', sa.DateTime(), nullable=False),
    sa.Column('dost_zdool', sa.Float(), nullable=False),
    sa.Column('elektrownia', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('business_date', sa.DateTime(), nullable=False),
    sa.Column('source_datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_forecast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stacja_nazwa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_pobrania_prognozy', sa.DateTime(), nullable=False),
    sa.Column('dzien_prognozy', sa.DateTime(), nullable=False),
    sa.Column('czas_prognozy', sa.DateTime(), nullable=False),
    sa.Column('temperatura_prognoza', sa.Float(), nullable=False),
    sa.Column('wilgotnosc_prognoza', sa.Float(), nullable=False),
    sa.Column('predkosc_wiatru_prognoza', sa.Float(), nullable=False),
    sa.Column('kierunek_wiatru_prognoza', sa.Integer(), nullable=True),
    sa.Column('szansa_opadu', sa.Float(), nullable=True),
    sa.Column('wielkosc_opadu_prognoza', sa.Float(), nullable=True),
    sa.Column('cisnienie_prognoza', sa.Float(), nullable=True),
    sa.Column('zachmurzenie_prognoza', sa.Float(), nullable=True),
    sa.Column('zrodlo_prognozy', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pogoda_prog_data_pobrania', 'weather_forecast', ['data_pobrania_prognozy'], unique=False)
    op.create_index('idx_pogoda_prog_stacja_dzien', 'weather_forecast', ['stacja_nazwa', 'dzien_prognozy'], unique=False)
    op.create_table('weatherdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stacja', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('szerokosc', sa.Float(), nullable=False),
    sa.Column('dlugosc', sa.Float(), nullable=False),
    sa.Column('czas', sa.DateTime(), nullable=False),
    sa.Column('data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('godzina', sa.Integer(), nullable=False),
    sa.Column('temperatura', sa.Float(), nullable=False),
    sa.Column('wilgotnosc', sa.Integer(), nullable=False),
    sa.Column('opad', sa.Float(), nullable=False),
    sa.Column('predkosc_wiatru', sa.Float(), nullable=False),
    sa.Column('kierunek_wiatru', sa.Integer(), nullable=False),
    sa.Column('cisnienie', sa.Float(), nullable=False),
    sa.Column('zachmurzenie', sa.Integer(), nullable=False),
    sa.Column('natezenie_swiatla', sa.Integer(), nullable=False),
    sa.Column('weather_code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stacja', 'czas', name='uq_weather_data_stacja_czas')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weatherdata')
    op.drop_index('idx_pogoda_prog_stacja_dzien', table_name='weather_forecast')
    op.drop_index('idx_pogoda_prog_data_pobrania', table_name='weather_forecast')
    op.drop_table('weather_forecast')
    op.drop_table('unit_power_losses')
    op.drop_table('unit_power_flows')
    op.drop_index(op.f('ix_system_data_doba'), table_name='system_data')
    op.drop_table('system_data')
    op.drop_index('idx_analyza_bledow_stacja_dni', table_name='error_analysis')
    op.drop_table('error_analysis')
    op.drop_index('idx_energy_price_doba_biz', table_name='energy_prices')
    op.drop_table('energy_prices')
    op.drop_index(op.f('ix_energy_price_forecasts_forecast_date'), table_name='energy_price_forecasts')
    op.drop_table('energy_price_forecasts')
    op.drop_table('co2_prices')
    # ### end Alembic commands ###
