"""Full Setup2

Revision ID: ec741e9f1a4f
Revises: b9e8426fe4be
Create Date: 2025-12-05 21:43:25.748873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ec741e9f1a4f'
down_revision: Union[str, Sequence[str], None] = 'b9e8426fe4be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crb_rozliczenia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doba', sa.DateTime(), nullable=False),
    sa.Column('udtczas', sa.DateTime(), nullable=False),
    sa.Column('cen_rozl', sa.Float(), nullable=False),
    sa.Column('ckoeb_rozl', sa.Float(), nullable=True),
    sa.Column('ceb_sr_rozl', sa.Float(), nullable=True),
    sa.Column('ceb_pp_rozl', sa.Float(), nullable=True),
    sa.Column('udtczas_oreb', sa.DateTime(), nullable=True),
    sa.Column('business_date', sa.DateTime(), nullable=False),
    sa.Column('source_datetime', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doba', 'udtczas', name='uq_crb_doba_udtczas')
    )
    op.create_index('idx_crb_doba_biz', 'crb_rozliczenia', ['doba', 'business_date'], unique=False)
    op.create_index(op.f('ix_crb_rozliczenia_doba'), 'crb_rozliczenia', ['doba'], unique=False)
    op.create_table('demand_kse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doba', sa.DateTime(), nullable=False),
    sa.Column('udtczas', sa.DateTime(), nullable=False),
    sa.Column('obciazenie', sa.Float(), nullable=False),
    sa.Column('udtczas_oreb', sa.DateTime(), nullable=True),
    sa.Column('business_date', sa.DateTime(), nullable=False),
    sa.Column('source_datetime', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doba', 'udtczas', name='uq_demand_kse_doba_udtczas')
    )
    op.create_index('idx_demand_kse_doba_biz', 'demand_kse', ['doba', 'business_date'], unique=False)
    op.create_index(op.f('ix_demand_kse_doba'), 'demand_kse', ['doba'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demand_kse_doba'), table_name='demand_kse')
    op.drop_index('idx_demand_kse_doba_biz', table_name='demand_kse')
    op.drop_table('demand_kse')
    op.drop_index(op.f('ix_crb_rozliczenia_doba'), table_name='crb_rozliczenia')
    op.drop_index('idx_crb_doba_biz', table_name='crb_rozliczenia')
    op.drop_table('crb_rozliczenia')
    # ### end Alembic commands ###
