"""Full Setup6

Revision ID: f3b56275a051
Revises: e22674a46a9f
Create Date: 2025-12-05 21:59:23.689129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f3b56275a051'
down_revision: Union[str, Sequence[str], None] = 'e22674a46a9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_crb_doba_udtczas', 'crb_rozliczenia', ['doba', 'udtczas_oreb'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_crb_doba_udtczas', 'crb_rozliczenia', type_='unique')
    # ### end Alembic commands ###
