"""add_pse_api_models

Revision ID: f75ca21a6d1c
Revises: 7f3f802d357f
Create Date: 2026-03-12 03:35:47.925172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f75ca21a6d1c'
down_revision: Union[str, Sequence[str], None] = '7f3f802d357f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregated_market_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dtime', sa.DateTime(), nullable=False),
    sa.Column('dtime_utc', sa.DateTime(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_utc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('business_date', sa.DateTime(), nullable=False),
    sa.Column('sk_cost', sa.Float(), nullable=False),
    sa.Column('contracting_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('publication_ts', sa.DateTime(), nullable=False),
    sa.Column('publication_ts_utc', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dtime', 'period', name='uq_market_position')
    )
    op.create_index(op.f('ix_aggregated_market_position_dtime'), 'aggregated_market_position', ['dtime'], unique=False)
    op.create_table('cross_border_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dtime', sa.DateTime(), nullable=False),
    sa.Column('dtime_utc', sa.DateTime(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_utc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('business_date', sa.DateTime(), nullable=False),
    sa.Column('section_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('publication_ts', sa.DateTime(), nullable=False),
    sa.Column('publication_ts_utc', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dtime', 'section_code', 'business_date', name='uq_flows')
    )
    op.create_index('idx_flows_dtime', 'cross_border_flows', ['dtime'], unique=False)
    op.create_index(op.f('ix_cross_border_flows_dtime'), 'cross_border_flows', ['dtime'], unique=False)
    op.create_index(op.f('ix_cross_border_flows_section_code'), 'cross_border_flows', ['section_code'], unique=False)
    op.create_table('demand_renewable_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dtime', sa.DateTime(), nullable=False),
    sa.Column('dtime_utc', sa.DateTime(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('business_date', sa.DateTime(), nullable=False),
    sa.Column('forecast_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('load_fcst', sa.Float(), nullable=True),
    sa.Column('load_actual', sa.Float(), nullable=True),
    sa.Column('publication_ts', sa.DateTime(), nullable=False),
    sa.Column('publication_ts_utc', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dtime', 'forecast_type', name='uq_demand_forecasts')
    )
    op.create_index('idx_demand_forecasts_dtime', 'demand_renewable_forecasts', ['dtime'], unique=False)
    op.create_index(op.f('ix_demand_renewable_forecasts_dtime'), 'demand_renewable_forecasts', ['dtime'], unique=False)
    op.create_table('generation_by_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dtime', sa.DateTime(), nullable=False),
    sa.Column('dtime_utc', sa.DateTime(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_utc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('business_date', sa.DateTime(), nullable=False),
    sa.Column('jgw1', sa.Float(), nullable=True),
    sa.Column('jgw2', sa.Float(), nullable=True),
    sa.Column('jgm1', sa.Float(), nullable=True),
    sa.Column('jgm2', sa.Float(), nullable=True),
    sa.Column('jgz1', sa.Float(), nullable=True),
    sa.Column('jgz2', sa.Float(), nullable=True),
    sa.Column('jgz3', sa.Float(), nullable=True),
    sa.Column('jga', sa.Float(), nullable=True),
    sa.Column('jgo', sa.Float(), nullable=True),
    sa.Column('jnwrb', sa.Float(), nullable=True),
    sa.Column('wi', sa.Float(), nullable=True),
    sa.Column('pv', sa.Float(), nullable=True),
    sa.Column('zapotrzebowanie', sa.Float(), nullable=False),
    sa.Column('swm_p', sa.Float(), nullable=True),
    sa.Column('swm_np', sa.Float(), nullable=True),
    sa.Column('jg', sa.Float(), nullable=True),
    sa.Column('publication_ts', sa.DateTime(), nullable=False),
    sa.Column('publication_ts_utc', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dtime', 'business_date', name='uq_generation_dtime_biz')
    )
    op.create_index('idx_generation_dtime', 'generation_by_source', ['dtime'], unique=False)
    op.create_index(op.f('ix_generation_by_source_business_date'), 'generation_by_source', ['business_date'], unique=False)
    op.create_index(op.f('ix_generation_by_source_dtime'), 'generation_by_source', ['dtime'], unique=False)
    op.create_table('intraday_trading_volume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dtime', sa.DateTime(), nullable=False),
    sa.Column('dtime_utc', sa.DateTime(), nullable=False),
    sa.Column('business_date', sa.DateTime(), nullable=False),
    sa.Column('market_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('day_ahead_tr_vol', sa.Float(), nullable=True),
    sa.Column('sprz_volume', sa.Float(), nullable=True),
    sa.Column('publication_ts', sa.DateTime(), nullable=False),
    sa.Column('publication_ts_utc', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dtime', 'market_type', name='uq_intraday_volume')
    )
    op.create_index(op.f('ix_intraday_trading_volume_dtime'), 'intraday_trading_volume', ['dtime'], unique=False)
    op.create_table('sdac_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dtime', sa.DateTime(), nullable=False),
    sa.Column('dtime_utc', sa.DateTime(), nullable=False),
    sa.Column('period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_utc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('business_date', sa.DateTime(), nullable=False),
    sa.Column('csdac_pln', sa.Float(), nullable=False),
    sa.Column('publication_ts', sa.DateTime(), nullable=False),
    sa.Column('publication_ts_utc', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dtime', 'period', name='uq_sdac_prices')
    )
    op.create_index(op.f('ix_sdac_prices_dtime'), 'sdac_prices', ['dtime'], unique=False)
    op.drop_table('weatherdata')
    op.drop_index(op.f('idx_model_trained_at'), table_name='model_metadata')
    op.drop_index(op.f('ix_model_metadata_model_name'), table_name='model_metadata')
    op.drop_index(op.f('ix_model_metadata_trained_at'), table_name='model_metadata')
    op.drop_table('model_metadata')
    op.drop_index(op.f('idx_analyza_bledow_stacja_dni'), table_name='error_analysis')
    op.drop_table('error_analysis')
    op.drop_index(op.f('ix_energy_price_forecasts_forecast_date'), table_name='energy_price_forecasts')
    op.drop_table('energy_price_forecasts')
    op.drop_index(op.f('ix_system_data_doba'), table_name='system_data')
    op.drop_table('system_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doba', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('temperatura', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('predkosc_wiatru', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('zamoralowienie', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('prognoza_popytu', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('produkcja_oze', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('godzina', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('system_data_pkey'))
    )
    op.create_index(op.f('ix_system_data_doba'), 'system_data', ['doba'], unique=False)
    op.create_table('energy_price_forecasts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('forecast_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('prognoza_cena_mwh', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('godzina', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('publication_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('energy_price_forecasts_pkey'))
    )
    op.create_index(op.f('ix_energy_price_forecasts_forecast_date'), 'energy_price_forecasts', ['forecast_date'], unique=False)
    op.create_table('error_analysis',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stacja_nazwa', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('dni_wyprzedzenia', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('blad_temperatury', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('blad_wiatru', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('blad_opadow', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('blad_zachmurzenia', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('czy_prognoza_byla_dokladna', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('error_analysis_pkey'))
    )
    op.create_index(op.f('idx_analyza_bledow_stacja_dni'), 'error_analysis', ['stacja_nazwa', 'dni_wyprzedzenia'], unique=False)
    op.create_table('model_metadata',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('mae', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('rmse', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('r2_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('model_file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('model_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('training_data_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feature_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('training_duration_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('trained_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('model_metadata_pkey')),
    sa.UniqueConstraint('model_name', 'version', name=op.f('uq_model_name_version'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_model_metadata_trained_at'), 'model_metadata', ['trained_at'], unique=False)
    op.create_index(op.f('ix_model_metadata_model_name'), 'model_metadata', ['model_name'], unique=False)
    op.create_index(op.f('idx_model_trained_at'), 'model_metadata', ['trained_at'], unique=False)
    op.create_table('weatherdata',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stacja', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('szerokosc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('dlugosc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('czas', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('data', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('godzina', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('temperatura', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('wilgotnosc', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('opad', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('predkosc_wiatru', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('kierunek_wiatru', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cisnienie', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('zachmurzenie', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('natezenie_swiatla', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weather_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('weatherdata_pkey')),
    sa.UniqueConstraint('stacja', 'czas', name=op.f('uq_weather_data_stacja_czas'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_sdac_prices_dtime'), table_name='sdac_prices')
    op.drop_table('sdac_prices')
    op.drop_index(op.f('ix_intraday_trading_volume_dtime'), table_name='intraday_trading_volume')
    op.drop_table('intraday_trading_volume')
    op.drop_index(op.f('ix_generation_by_source_dtime'), table_name='generation_by_source')
    op.drop_index(op.f('ix_generation_by_source_business_date'), table_name='generation_by_source')
    op.drop_index('idx_generation_dtime', table_name='generation_by_source')
    op.drop_table('generation_by_source')
    op.drop_index(op.f('ix_demand_renewable_forecasts_dtime'), table_name='demand_renewable_forecasts')
    op.drop_index('idx_demand_forecasts_dtime', table_name='demand_renewable_forecasts')
    op.drop_table('demand_renewable_forecasts')
    op.drop_index(op.f('ix_cross_border_flows_section_code'), table_name='cross_border_flows')
    op.drop_index(op.f('ix_cross_border_flows_dtime'), table_name='cross_border_flows')
    op.drop_index('idx_flows_dtime', table_name='cross_border_flows')
    op.drop_table('cross_border_flows')
    op.drop_index(op.f('ix_aggregated_market_position_dtime'), table_name='aggregated_market_position')
    op.drop_table('aggregated_market_position')
    # ### end Alembic commands ###
